# Generated by Django 4.0.4 on 2022-06-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userinfo_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='iddefault',
            new_name='isdefault',
        ),
    ]
